FROM eclipse-temurin:21-jre
COPY ./tika-server/tika-server-standard/target/tika-server-standard-3.3.0.jar /app/tika.jar
EXPOSE 9998
ENV _JAVA_OPTIONS "-XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=80.0"
CMD java -jar /app/tika.jar -host 0.0.0.0 -port 9998
